name: 'Notion PR Checker'
description: 'Checks the existence of a Notion Issue'
inputs:
  notion-secret:
    description: 'Secret for accessing Notion API'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
