name: 'Notion PR Checker'
description: 'Checks the existence of a Notion Issue'
inputs:
  notion-secret:
    description: 'Secret for accessing Notion API'
    required: true
  notion-database:
    description: 'Task database'
    required: true
  token:
    description: 'Required GH token to use the API to get latest title'
    required: true
outputs:
  notion_task:
    description: Result task ID

runs:
  using: 'node16'
  main: 'dist/index.js'
